"""empty message

Revision ID: 825d5878cecb
Revises: 58c4e943fbd7
Create Date: 2020-06-25 14:52:13.094105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825d5878cecb'
down_revision = '58c4e943fbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_categories', sa.Column('image_id', sa.String(length=150), nullable=True))
    op.add_column('dish_categories', sa.Column('image_path', sa.String(length=150), nullable=True))
    op.add_column('dishes', sa.Column('show_usd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'show_usd')
    op.drop_column('dish_categories', 'image_path')
    op.drop_column('dish_categories', 'image_id')
    # ### end Alembic commands ###
